// . Write a C program to generate Fibonacci sequence upto nth term where n is an input have to be taken
// from the keyboard. Write a main program to test it. The Fibonacci numbers are generated by setting
// F0 = 0, F1 = 1 and using the following formula to get the rest.
// Fn = Fn−1 + Fn−2

#include<stdio.h>

int main(){
    int n,a = 0, b = 1, next;

    printf("enter number of terms:");
    scanf("%d", &n);
    printf("the  fibbonachi sequence upto given terms is ");
    for (int i = 0; i < n; i++)
    {
         printf("%d", a);
        next = a + b;
        a = b;
        b = next;
       
    }
    return 0;
}